### ISSUE TITLE
Section mist een heading

### ISSUE THREAD

**Issue by koeenm** [SamaraFellaDina/the-startup-responsive-interactieve-website#15]
probeer een extra heading, zoals een h2, toe te voegen bij elke section zodat deze te identificeren zijn, of gebruik een div als er geen heading nodig is

From line 25, column 9; to line 25, column 39

https://github.com/SamaraFellaDina/the-startup-responsive-interactieve-website/blob/54cca5300d04ec71328d2ec683d7003132678311/index.html#L25

**Comment by SamaraFellaDina** [comment]
Ow ja want die zit er wel in, alleen hij zit verwerkt in het `<article>` binnen die section. Dat is prima toch? Ik weet namelijk ook niet of het zo per se goed is :)

https://github.com/SamaraFellaDina/the-startup-responsive-interactieve-website/blob/54cca5300d04ec71328d2ec683d7003132678311/index.html#L25-L27
