### ISSUE TITLE
de value van "for" moet overeenkomen met de "id" 

### ISSUE THREAD

**Issue by koeenm** [SamaraFellaDina/the-startup-responsive-interactieve-website#16]
<img src="https://github.com/SamaraFellaDina/the-startup-responsive-interactieve-website/assets/144009715/29e1a77a-ce55-4aa1-8559-951103bc97a1">

je id moet dezelfde naam hebben als de value voor "for", dus <label id="email">

https://github.com/SamaraFellaDina/the-startup-responsive-interactieve-website/blob/54cca5300d04ec71328d2ec683d7003132678311/index.html#L46

![](https://media.giphy.com/media/SHQPfVrV7OpLW/giphy.gif)

**Comment by SamaraFellaDina** [comment]
gedaan!

https://github.com/SamaraFellaDina/the-startup-responsive-interactieve-website/blob/1a553ff2b9b74a9e0aa27ba038e7901cb376d20a/index.html#L45-L57
