### ISSUE TITLE
Probeer eens duidelijkere class naming! :)

### ISSUE THREAD

**Issue by itsValyria** [SamaraFellaDina/the-startup-responsive-interactieve-website#17]
Als kleine tip voor je class naming, zou ik proberen om BEM benaming (of iets soortgelijks) uit te proberen. Je kunt dan in de CSS heel snel zien waar iets bij hoort. Zo kun je je classes duidelijk toedelen aan header, main, footer of een ander groot element.

Voorbeelden hiervan zijn:
```css
.download-form --> .download__form {}
.download-form-input --> .download__form--input {}
``` 
etc.

Hier kun je er meer over lezen:
https://getbem.com/naming/

Btw, this is for not following me back at Github:
![](https://media.giphy.com/media/5qFDrz8CE75GzT9qJW/giphy.gif)

**Comment by SamaraFellaDina** [comment]
hee ik zag deze al staan! Echt goed, is eigenlijk zoveel handiger! Volgende keer zal ik dit toepassen :) 

En ik volg je wel hoor >:(

![](https://media.giphy.com/media/IUxFvKwD3jXisqR5w7/giphy.gif)
