### ISSUE TITLE
Waarom gebruik je een <br> element?

### ISSUE THREAD

**Issue by itsValyria** [SamaraFellaDina/the-startup-responsive-interactieve-website#18]
Honest question, waarom gebruik je <br> elements in je HTML?

https://github.com/SamaraFellaDina/the-startup-responsive-interactieve-website/blob/54cca5300d04ec71328d2ec683d7003132678311/index.html#L46-L56

Ik ben vrij zeker dat je dat op een andere manier kan oplossen! Denk zelfs dat het nog gewoon werkt als je het weghaalt.

Hier kan je er meer informatie over lezen, mocht dat nodig zijn:
https://blog.hubspot.com/website/html-line-break#:~:text=The%20HTML%20element%20is,or%20structure%20in%20your%20content.

**Comment by SamaraFellaDina** [comment]
Opgelost!

https://github.com/SamaraFellaDina/the-startup-responsive-interactieve-website/blob/49457cbc95b3c4a8d6bfb59e357b25d1923d231d/index.html#L45-L59
