### ISSUE TITLE
The value of the for attribute of the label element must be the ID of a non-hidden form control.

### ISSUE THREAD

**Issue by itsValyria** [SamaraFellaDina/the-startup-responsive-interactieve-website#19]
Link naar betreffende code:
https://github.com/SamaraFellaDina/the-startup-responsive-interactieve-website/blob/54cca5300d04ec71328d2ec683d7003132678311/index.html#L46C1-L56C34

Je maakt gebruik van een label element, en heeft die een ''for'' attribute gegeven, je moet dan altijd ook een ID mee geven met dezelfde naam.

Hier kun je er meer informatie over lezen:
https://stackoverflow.com/questions/38569235/the-for-attribute-of-the-label-element-must-refer-to-a-non-hidden-form-control

**Comment by SamaraFellaDina** [comment]
Opgelost :)

https://github.com/SamaraFellaDina/the-startup-responsive-interactieve-website/blob/1a553ff2b9b74a9e0aa27ba038e7901cb376d20a/index.html#L45-L57
