### ISSUE TITLE
Spelfoutje

### ISSUE THREAD

**Issue by DamianR2004** [SamaraFellaDina/the-startup-responsive-interactieve-website#2]
https://github.com/SamaraFellaDina/the-startup-responsive-interactieve-website/blob/195d864416cec116867d75b551ae2fcf69d5b650/styles/style.css#L12-L15

Volgens mij bedoel je Primary🤓

![The Bradge](https://i.makeagif.com/media/6-29-2023/9FOBNG.gif)

**Comment by SamaraFellaDina** [comment]
Aangepast!
