### ISSUE TITLE
Probeer custom properties te gebruiken voor meer dan alleen kleur

### ISSUE THREAD

**Issue by lisagjh** [SamaraFellaDina/the-startup-responsive-interactieve-website#24]
Je gebruikt vaak dezelfde margins en paddings, hier kan je ook custom properties voor gebruiken!

https://github.com/SamaraFellaDina/the-startup-responsive-interactieve-website/blob/54cca5300d04ec71328d2ec683d7003132678311/styles/style.css#L11-L21

Dit is hoe ik het doe:

https://github.com/lisagjh/the-startup/blob/847b84401b571b6108d7f89b03d5b0601b229575/style/style.css#L70-L73

Als je dan toch nog een andere grootte nodig heb, kan je dat altijd nog op element niveau opnieuw declaren:

https://github.com/lisagjh/the-startup/blob/847b84401b571b6108d7f89b03d5b0601b229575/style/style.css#L186-L187

**Comment by SamaraFellaDina** [comment]
Ik heb mijn fonts erin gedaan! Als je bij meer dingen hebt van joh, dat kan ook als custom property hoor ik het graag ;)

https://github.com/SamaraFellaDina/the-startup-responsive-interactieve-website/blob/bdc6de51828c8c84617935aaabb6be0cad9e5189/styles/style.css#L21-L22
