### ISSUE TITLE
Erg gaaf ontwerp

### ISSUE THREAD

**Issue by lisagjh** [SamaraFellaDina/the-startup-responsive-interactieve-website#25]
Je ontwerp is echt heel gaaf. ook leuk bij de download section dat je dit zo krijgt. Heel leuk!! Lekker bezig!! :D

![afbeelding](https://github.com/SamaraFellaDina/the-startup-responsive-interactieve-website/assets/131701505/da6b894a-a0e0-4d25-bd92-2aa124cde5c5)

**Comment by SamaraFellaDina** [comment]
jaa dankjewel! Met bloed zweet en tranen is het gelukt. Ben er heel blij mee :)

![](https://media.giphy.com/media/TdfyKrN7HGTIY/giphy.gif)
