### ISSUE TITLE
Goed bezig

### ISSUE THREAD

**Issue by DamianR2004** [SamaraFellaDina/the-startup-responsive-interactieve-website#4]
CSS en HTML zien er goed uit! Leuk ook dat je zelf de svg's zelf heb gemaakt.

![](https://media.tenor.com/I5SPx34_vKIAAAAi/koetlife.gif) 👍

**Comment by SamaraFellaDina** [comment]
Dankjewel! mocht je een SVG of mockup nodig hebben, laat maar weten
