### ISSUE TITLE
Navbar 

### ISSUE THREAD

**Issue by Vikkeyeftimov** [SamaraFellaDina/the-startup-responsive-interactieve-website#5]
je hebt helemaal geen navbar

**Comment by SamaraFellaDina** [comment]
nee klopt! ga ik volgende week naar kijken!

**Comment by SamaraFellaDina** [comment]
Moet eigenlijk wel, maar vind ik niet relevant voor deze opdracht ;)

![](https://media.giphy.com/media/B0vFTrb0ZGDf2/giphy.gif)
