### ISSUE TITLE
Geen fallback fonts

### ISSUE THREAD

**Issue by aliceafanasieva** [SamaraFellaDina/the-startup-responsive-interactieve-website#8]
Misschien is het handig een fallback font te hebben in het geval dat jouw font niet werkt.

**Comment by SamaraFellaDina** [comment]
Goed dat je het aangeeft! ik wil binnenkort de fallback fonts in mijn `:root` zetten zodat het ook DRY wordt

**Comment by SamaraFellaDina** [comment]
Ik heb mijn fonts erin gedaan! Als je bij meer dingen hebt van joh, dat kan ook als custom property hoor ik het graag ;)

https://github.com/SamaraFellaDina/the-startup-responsive-interactieve-website/blob/bdc6de51828c8c84617935aaabb6be0cad9e5189/styles/style.css#L21-L22
