### ISSUE TITLE
main content in center

### ISSUE THREAD

**Issue by aliceafanasieva** [SamaraFellaDina/the-startup-responsive-interactieve-website#9]
Misschien de main content centreren zometeen.

![](https://media.giphy.com/media/xr9AQyxLtjlx4IeYtN/giphy.gif)

**Comment by SamaraFellaDina** [comment]
Ben er mee bezig!

**Comment by SamaraFellaDina** [comment]
Is helemaal gelukt!

https://samarafelladina.github.io/the-startup-responsive-interactieve-website/
